# -*- coding: utf-8 -*-
"""Friday_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_rfZgvolmzyD4bb85PSDSsTNmOxif_EH
"""

def remove_and_sort(Lin, k):
    """ Lin is a list of ints
        k is an int >= 0
    Mutates Lin to remove the first k elements in Lin and
    then sorts the remaining elements in ascending order.
    If you run out of items to remove, Lin is mutated to an empty list.
    Does not return anything.
    """
    del Lin[:k]  # Remove the first k elements
    Lin.sort()   # Sort the remaining elements
L = [1, 2, 6, 3]
k = 1
remove_and_sort(L, k)
print(L)

